[CDF-26621] 🐛Pull view issue (#2367)
# Description

User error message
```
NotImplementedError: Missing implementation for ViewCRUD for filter.hasData.
```

## Bump

- [x] Patch
- [ ] Skip

## Changelog

### Fixed

- Running `cdf modules pull` with a view with filters no longer raises a
`NotImplementedError`.