[CDF-27233] 🐛 Handle metadata (#2588)
# Description

User met with 

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for DataSetRequest
metadata.archived
  Input should be a valid string [type=string_type, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.12/v/string_type
```

## Bump

- [x] Patch
- [ ] Skip

## Changelog

### Fixed

- Deploying any resource with metadata field no longer requires that
field to be string.