[CDF-25530] 🦂 Chunk transformations (#1843)
# Description

The `/createTransformations` and `updateTransformations` supports up to
1000 items per requests in the API spec. However, in practice it starts
to fail with
```
Failed to bind nonce with session for externalId='myTransformation', Failed to bind session using nonce for: 4085469897442439
 | code: 400 | X-Request-ID: cdb06f95-91e9-9d44-8734-6205f2110003 | cluster: bluefield
```
and 
```
CogniteAPIError: Service unavailable | code: 503 | X-Request-ID: c3f134df-78aa-9e8a-a786-ef6fb7364a09 | cluster: bluefield
```

if you try to create/update a few 100 transformations with credentials.
[Ref
slack](https://cognitedata.slack.com/archives/C0654Q63B6H/p1755241631506179).

This PR introduces a batch size of 20 of non-concurrent calls to the
transformation API to avoid triggering this issue.

## Changelog

- [x] Patch
- [ ] Skip

## cdf

### Fixed

- When deploying in the order of 100s of Transformations, Toolkit should
no longer cause a 400 response and fail with `Failed to bind nonce with
session for...`.

## templates

No changes.