[CDF-28575] 🐛 fix: hosted extracto jobs update (#3223)
# Description

Please describe the change you have made.

## Bump

- [x] Patch
- [ ] Skip

## Changelog

### Fixed

- When upading HostedExtractorJobs that has the `config` property not
set with the `cdf deploy` command, Toolkit no longer raise a `ERROR
(ResourceUpdateError): Failed to update hosted extractor jobs due to API
error: Request failed with status code 422: items[0].update.config.set`
error.